name: Benchmark vs GHA
on:
  pull_request:
    branches:
      - main
    paths:
      - .github/worflows/benchmark-vs-gha.yaml
  push:
    branches:
      - vs-gha
  
env:
  DOCKER_BUILDKIT: 1

jobs:
  gha:
    name: build with gha
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      
      - name: checkout distribution/distribution
        uses: actions/checkout@v3
        with:
          repository: distribution/distribution
          fetch-depth: 1
          path: ./tmp

      - uses: docker/build-push-action@v2
        with:
          context: ./tmp
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

